title: Alan的个人博客
email: taojiang48#gmail.com
description: Alan的个人博客，记录生活中一些有趣的事情
    ，翻译，文摘......
url: "http://martyjiang.github.io"
github_username:  MartyJiang
encoding: utf-8
markdown: kramdown
include: [./imgs]
